# coding: utf-8

"""
    IONOS DBaaS MariaDB REST API

    An enterprise-grade Database is provided as a Service (DBaaS) solution that can be managed through a browser-based \"Data Center Designer\" (DCD) tool or via an easy to use API.  The API allows you to create additional MariaDB database clusters or modify existing ones. It is designed to allow users to leverage the same power and flexibility found within the DCD visual tool. Both tools are consistent with their concepts and lend well to making the experience smooth and intuitive. 

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from ionoscloud_dbaas_mariadb.models.base_backup import BaseBackup
from typing import Optional, Set
from typing_extensions import Self

class Backup(BaseModel):
    """
    A backup object.
    """ # noqa: E501
    cluster_id: Optional[StrictStr] = Field(default=None, description="The unique ID of the cluster that was backed up.", alias="clusterId")
    location: Optional[StrictStr] = Field(default=None, description="The S3 location where the backups will be stored.")
    earliest_recovery_target_time: Optional[datetime] = Field(default=None, description="The oldest available timestamp to which you can restore.", alias="earliestRecoveryTargetTime")
    size: Optional[StrictInt] = Field(default=None, description="Size of all base backups in MiB. This is at least the sum of all base backup sizes. ")
    base_backups: Optional[List[BaseBackup]] = Field(default=None, alias="baseBackups")
    __properties: ClassVar[List[str]] = ["clusterId", "location", "earliestRecoveryTargetTime", "size", "baseBackups"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Backup from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in base_backups (list)
        _items = []
        if self.base_backups:
            for _item_base_backups in self.base_backups:
                if _item_base_backups:
                    _items.append(_item_base_backups.to_dict())
            _dict['baseBackups'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Backup from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "clusterId": obj.get("clusterId"),
            "location": obj.get("location"),
            "earliestRecoveryTargetTime": obj.get("earliestRecoveryTargetTime"),
            "size": obj.get("size"),
            "baseBackups": [BaseBackup.from_dict(_item) for _item in obj["baseBackups"]] if obj.get("baseBackups") is not None else None
        })
        return _obj


