# coding: utf-8

"""
    IONOS DBaaS MariaDB REST API

    An enterprise-grade Database is provided as a Service (DBaaS) solution that can be managed through a browser-based \"Data Center Designer\" (DCD) tool or via an easy to use API.  The API allows you to create additional MariaDB database clusters or modify existing ones. It is designed to allow users to leverage the same power and flexibility found within the DCD visual tool. Both tools are consistent with their concepts and lend well to making the experience smooth and intuitive. 

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from ionoscloud_dbaas_mariadb.models.state import State
from typing import Optional, Set
from typing_extensions import Self

class ClusterMetadata(BaseModel):
    """
    Metadata of the resource.
    """ # noqa: E501
    created_date: Optional[datetime] = Field(default=None, description="The ISO 8601 creation timestamp.", alias="createdDate")
    created_by: Optional[StrictStr] = Field(default=None, alias="createdBy")
    created_by_user_id: Optional[StrictStr] = Field(default=None, alias="createdByUserId")
    last_modified_date: Optional[datetime] = Field(default=None, description="The ISO 8601 modified timestamp.", alias="lastModifiedDate")
    last_modified_by: Optional[StrictStr] = Field(default=None, alias="lastModifiedBy")
    last_modified_by_user_id: Optional[StrictStr] = Field(default=None, alias="lastModifiedByUserId")
    state: Optional[State] = None
    __properties: ClassVar[List[str]] = ["createdDate", "createdBy", "createdByUserId", "lastModifiedDate", "lastModifiedBy", "lastModifiedByUserId", "state"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ClusterMetadata from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ClusterMetadata from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "createdDate": obj.get("createdDate"),
            "createdBy": obj.get("createdBy"),
            "createdByUserId": obj.get("createdByUserId"),
            "lastModifiedDate": obj.get("lastModifiedDate"),
            "lastModifiedBy": obj.get("lastModifiedBy"),
            "lastModifiedByUserId": obj.get("lastModifiedByUserId"),
            "state": obj.get("state")
        })
        return _obj


