# coding: utf-8

"""
    IONOS DBaaS MariaDB REST API

    An enterprise-grade Database is provided as a Service (DBaaS) solution that can be managed through a browser-based \"Data Center Designer\" (DCD) tool or via an easy to use API.  The API allows you to create additional MariaDB database clusters or modify existing ones. It is designed to allow users to leverage the same power and flexibility found within the DCD visual tool. Both tools are consistent with their concepts and lend well to making the experience smooth and intuitive. 

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from ionoscloud_dbaas_mariadb.models.backup_properties import BackupProperties
from ionoscloud_dbaas_mariadb.models.connection import Connection
from ionoscloud_dbaas_mariadb.models.maintenance_window import MaintenanceWindow
from ionoscloud_dbaas_mariadb.models.mariadb_version import MariadbVersion
from typing import Optional, Set
from typing_extensions import Self

class ClusterProperties(BaseModel):
    """
    Properties of a database cluster.
    """ # noqa: E501
    display_name: Optional[Annotated[str, Field(strict=True, max_length=63)]] = Field(default=None, description="The friendly name of your cluster.", alias="displayName")
    mariadb_version: Optional[MariadbVersion] = Field(default=None, alias="mariadbVersion")
    dns_name: Optional[StrictStr] = Field(default=None, description="The DNS name pointing to your cluster.", alias="dnsName")
    instances: Optional[Annotated[int, Field(le=5, strict=True, ge=1)]] = Field(default=None, description="The total number of instances in the cluster (one primary and n-1 secondary). ")
    ram: Optional[Annotated[int, Field(strict=True, ge=4)]] = Field(default=None, description="The amount of memory per instance in gigabytes (GB).")
    cores: Optional[Annotated[int, Field(strict=True, ge=1)]] = Field(default=None, description="The number of CPU cores per instance.")
    storage_size: Optional[Annotated[int, Field(le=2000, strict=True, ge=10)]] = Field(default=None, description="The amount of storage per instance in gigabytes (GB).", alias="storageSize")
    connections: Optional[Annotated[List[Connection], Field(min_length=1, max_length=1)]] = None
    maintenance_window: Optional[MaintenanceWindow] = Field(default=None, alias="maintenanceWindow")
    backup: Optional[BackupProperties] = None
    __properties: ClassVar[List[str]] = ["displayName", "mariadbVersion", "dnsName", "instances", "ram", "cores", "storageSize", "connections", "maintenanceWindow", "backup"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ClusterProperties from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in connections (list)
        _items = []
        if self.connections:
            for _item_connections in self.connections:
                if _item_connections:
                    _items.append(_item_connections.to_dict())
            _dict['connections'] = _items
        # override the default output from pydantic by calling `to_dict()` of maintenance_window
        if self.maintenance_window:
            _dict['maintenanceWindow'] = self.maintenance_window.to_dict()
        # override the default output from pydantic by calling `to_dict()` of backup
        if self.backup:
            _dict['backup'] = self.backup.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ClusterProperties from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "displayName": obj.get("displayName"),
            "mariadbVersion": obj.get("mariadbVersion"),
            "dnsName": obj.get("dnsName"),
            "instances": obj.get("instances"),
            "ram": obj.get("ram"),
            "cores": obj.get("cores"),
            "storageSize": obj.get("storageSize"),
            "connections": [Connection.from_dict(_item) for _item in obj["connections"]] if obj.get("connections") is not None else None,
            "maintenanceWindow": MaintenanceWindow.from_dict(obj["maintenanceWindow"]) if obj.get("maintenanceWindow") is not None else None,
            "backup": BackupProperties.from_dict(obj["backup"]) if obj.get("backup") is not None else None
        })
        return _obj


