# coding: utf-8

"""
    IONOS DBaaS MariaDB REST API

    An enterprise-grade Database is provided as a Service (DBaaS) solution that can be managed through a browser-based \"Data Center Designer\" (DCD) tool or via an easy to use API.  The API allows you to create additional MariaDB database clusters or modify existing ones. It is designed to allow users to leverage the same power and flexibility found within the DCD visual tool. Both tools are consistent with their concepts and lend well to making the experience smooth and intuitive. 

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from ionoscloud_dbaas_mariadb.models.maintenance_window import MaintenanceWindow
from ionoscloud_dbaas_mariadb.models.mariadb_version import MariadbVersion
from typing import Optional, Set
from typing_extensions import Self

class PatchClusterProperties(BaseModel):
    """
    Properties of the payload to change a cluster: - instances can only be increased (3, 5, 7), - mariadbVersion can only be increased (no downgrade) - storageSize can only be increased, - ram and cores can be both increased and decreased. 
    """ # noqa: E501
    mariadb_version: Optional[MariadbVersion] = Field(default=None, alias="mariadbVersion")
    instances: Optional[Annotated[int, Field(le=5, strict=True, ge=1)]] = Field(default=None, description="The total number of instances in the cluster (one primary and n-1 secondary). ")
    cores: Optional[Annotated[int, Field(strict=True, ge=1)]] = Field(default=None, description="The number of CPU cores per instance.")
    ram: Optional[Annotated[int, Field(strict=True, ge=4)]] = Field(default=None, description="The amount of memory per instance in gigabytes (GB).")
    storage_size: Optional[Annotated[int, Field(le=2000, strict=True, ge=10)]] = Field(default=None, description="The amount of storage per instance in gigabytes (GB).", alias="storageSize")
    display_name: Optional[Annotated[str, Field(strict=True, max_length=63)]] = Field(default=None, description="The friendly name of your cluster.", alias="displayName")
    maintenance_window: Optional[MaintenanceWindow] = Field(default=None, alias="maintenanceWindow")
    __properties: ClassVar[List[str]] = ["mariadbVersion", "instances", "cores", "ram", "storageSize", "displayName", "maintenanceWindow"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PatchClusterProperties from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of maintenance_window
        if self.maintenance_window:
            _dict['maintenanceWindow'] = self.maintenance_window.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PatchClusterProperties from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "mariadbVersion": obj.get("mariadbVersion"),
            "instances": obj.get("instances"),
            "cores": obj.get("cores"),
            "ram": obj.get("ram"),
            "storageSize": obj.get("storageSize"),
            "displayName": obj.get("displayName"),
            "maintenanceWindow": MaintenanceWindow.from_dict(obj["maintenanceWindow"]) if obj.get("maintenanceWindow") is not None else None
        })
        return _obj


