# coding: utf-8

"""
    IONOS DBaaS MariaDB REST API

    An enterprise-grade Database is provided as a Service (DBaaS) solution that can be managed through a browser-based \"Data Center Designer\" (DCD) tool or via an easy to use API.  The API allows you to create additional MariaDB database clusters or modify existing ones. It is designed to allow users to leverage the same power and flexibility found within the DCD visual tool. Both tools are consistent with their concepts and lend well to making the experience smooth and intuitive. 

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class State(str, Enum):
    """
    The current status reported back by the cluster.
    """

    """
    allowed enum values
    """
    AVAILABLE = 'AVAILABLE'
    BUSY = 'BUSY'
    CREATING = 'CREATING'
    UPDATING = 'UPDATING'
    RESTORING = 'RESTORING'
    DESTROYING = 'DESTROYING'
    DEGRADED = 'DEGRADED'
    FAILED = 'FAILED'
    UNKNOWN = 'UNKNOWN'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of State from a JSON string"""
        return cls(json.loads(json_str))


